import { ArrowDownToLine, BriefcaseBusiness, Clock3, FolderKanban, Pause, Play } from 'lucide-react'
import { EmptyState } from '../components/common/EmptyState'
import { LiveTimer } from '../components/common/LiveTimer'
import { StatCard } from '../components/common/StatCard'
import { formatCurrency, formatMinutes } from '../lib/formatters'

export function DashboardPage({ activeTimer, projects, timerProject, setTimerProject, startTimer, stopTimer, report, range, setRange, entries, onEditEntry, onDeleteEntry }) {
  const timerRunning = Boolean(activeTimer?.id && activeTimer?.start_time)
  const activeProjects = projects.filter((project) => project.is_active)

  return <div className="page">
    <div className="page-heading"><div><p className="eyebrow">{new Intl.DateTimeFormat('pt-BR', { dateStyle: 'full' }).format(new Date())}</p><h1>Bom dia, vamos trabalhar?</h1><p className="subtitle">Acompanhe seu tempo sem tirar o foco do que importa.</p></div><PeriodTabs range={range} setRange={setRange} /></div>
    <section className="timer-card"><div className="timer-copy"><div className={`status-dot ${timerRunning ? 'running' : ''}`} /><div><p className="card-kicker">{timerRunning ? 'TRABALHO EM ANDAMENTO' : 'PRONTO PARA COMEÇAR?'}</p><h2>{timerRunning ? activeTimer.project?.name : 'O que você vai fazer agora?'}</h2>{timerRunning ? <p className="timer-start">Começou às {activeTimer.start_time?.slice(0, 5)} · {activeTimer.project?.client?.name}</p> : activeProjects.length ? <select aria-label="Projeto do timer" value={timerProject} onChange={(event) => setTimerProject(event.target.value)}><option value="">Selecione um projeto</option>{activeProjects.map((project) => <option key={project.id} value={project.id}>{project.name} · {project.client?.name}</option>)}</select> : <p className="timer-start">Cadastre um projeto ativo para iniciar o timer.</p>}</div></div><div className="timer-action">{timerRunning ? <><LiveTimer startedAt={activeTimer.start_time} /><button className="stop-button" onClick={stopTimer}><Pause size={17} fill="currentColor" /> Parar timer</button></> : <button className="start-button" disabled={!timerProject || !activeProjects.length} onClick={startTimer}><Play size={17} fill="currentColor" /> Iniciar timer</button>}</div></section>
    <div className="stat-grid"><StatCard icon={<Clock3 />} label="Horas registradas" value={formatMinutes(report.total_minutes)} detail="no período selecionado" /><StatCard icon={<BriefcaseBusiness />} label="Valor estimado" value={formatCurrency(report.total_amount)} detail="com base nas taxas" /><StatCard icon={<FolderKanban />} label="Projetos ativos" value={activeProjects.length} detail={`${projects.length} projetos no total`} /></div>
    <div className="content-grid"><ProjectSummary report={report} /><RecentEntries entries={entries} onEditEntry={onEditEntry} onDeleteEntry={onDeleteEntry} /></div>
  </div>
}

function PeriodTabs({ range, setRange }) { return <div className="period-tabs">{[['today', 'Hoje'], ['week', '7 dias'], ['month', 'Este mês']].map(([id, label]) => <button key={id} className={range === id ? 'selected' : ''} onClick={() => setRange(id)}>{label}</button>)}</div> }
function ProjectSummary({ report }) { return <section className="panel"><div className="panel-heading"><div><h2>Resumo por projeto</h2><p>Onde seu tempo está indo</p></div><ArrowDownToLine size={18} className="muted" /></div>{report.by_project?.length ? <div className="project-summary">{report.by_project.map((item) => <div className="summary-row" key={item.project_id}><div className="summary-icon"><FolderKanban size={16} /></div><div className="summary-name"><strong>{item.project}</strong><span>{item.client}</span></div><div className="summary-bar"><i style={{ width: `${Math.min(100, (item.minutes / Math.max(report.total_minutes, 1)) * 100)}%` }} /></div><div className="summary-time">{formatMinutes(item.minutes)}<small>{formatCurrency(item.amount)}</small></div></div>)}</div> : <EmptyState text="Ainda não há horas neste período." />}</section> }
function RecentEntries({ entries, onEditEntry, onDeleteEntry }) { return <section className="panel"><div className="panel-heading"><div><h2>Últimos lançamentos</h2><p>Seus registros mais recentes</p></div></div>{entries.length ? <div className="recent-list">{entries.slice(0, 5).map((entry) => <div className="recent-row" key={entry.id}><div className="date-badge"><strong>{new Date(`${entry.work_date}T12:00:00`).getDate()}</strong><span>{new Intl.DateTimeFormat('pt-BR', { month: 'short' }).format(new Date(`${entry.work_date}T12:00:00`)).replace('.', '')}</span></div><div className="recent-info"><strong>{entry.project?.name}</strong><span>{entry.description || 'Sem descrição'}</span></div><strong className="recent-time">{entry.duration_minutes ? formatMinutes(entry.duration_minutes) : 'ativo'}</strong><button className="mini-action" onClick={() => onEditEntry(entry)} aria-label="Editar"><span className="sr-only">Editar</span>✎</button><button className="mini-action danger" onClick={() => onDeleteEntry(entry)} aria-label="Excluir"><span className="sr-only">Excluir</span>×</button></div>)}</div> : <EmptyState text="Seus lançamentos aparecerão aqui." />}</section> }
