import { useState } from 'react'
import { Check, FolderKanban, Pencil, Plus, Trash2 } from 'lucide-react'
import { EmptyState } from '../components/common/EmptyState'
import { Field } from '../components/common/Field'
import { emptyProject } from '../lib/formDefaults'
import { formatCurrency } from '../lib/formatters'

export function ProjectsPage({ projects, clients, onCreate, onUpdate, onDelete }) {
  const [form, setForm] = useState(emptyProject())
  const [editing, setEditing] = useState(null)
  const submit = (event) => { event.preventDefault(); const payload = { ...form, client_id: Number(form.client_id), hourly_rate: Number(form.hourly_rate) }; Promise.resolve(editing ? onUpdate(editing.id, payload) : onCreate(payload)).then((success) => { if (success) { setForm(emptyProject()); setEditing(null) } }) }
  const edit = (project) => { setEditing(project); setForm({ client_id: String(project.client_id), name: project.name, description: project.description || '', hourly_rate: String(project.hourly_rate) }) }
  const cancel = () => { setEditing(null); setForm(emptyProject()) }
  const remove = (project) => { if (window.confirm(`Excluir o projeto “${project.name}”? Esta ação não pode ser desfeita.`)) onDelete(project.id) }
  return <div className="page"><div className="page-heading compact"><div><p className="eyebrow">ORGANIZAÇÃO</p><h1>Projetos</h1><p className="subtitle">Defina uma taxa para cada trabalho.</p></div></div><div className="content-grid"><section className="panel form-panel"><div className="panel-heading"><div><h2>{editing ? 'Editar projeto' : 'Novo projeto'}</h2><p>{editing ? 'Atualize as informações do projeto.' : 'Comece a organizar seu trabalho.'}</p></div>{editing && <button className="text-button" type="button" onClick={cancel}>Cancelar</button>}</div><form className="stack-form" onSubmit={submit}><Field label="Cliente"><select required value={form.client_id} onChange={(event) => setForm({ ...form, client_id: event.target.value })}><option value="">Selecione...</option>{clients.filter((client) => client.is_active).map((client) => <option key={client.id} value={client.id}>{client.name}</option>)}</select></Field><Field label="Nome do projeto"><input required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} placeholder="Ex.: Site institucional" /></Field><Field label="Valor por hora"><input required type="number" min="0" step="0.01" value={form.hourly_rate} onChange={(event) => setForm({ ...form, hourly_rate: event.target.value })} /></Field><Field label="Descrição"><textarea rows="3" value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} /></Field><button className="primary-button" type="submit">{editing ? <><Check size={17} /> Salvar alterações</> : <><Plus size={17} /> Criar projeto</>}</button></form></section><section className="panel"><div className="panel-heading"><div><h2>Seus projetos</h2><p>{projects.length} projeto(s) cadastrado(s)</p></div></div><div className="cards-list">{projects.map((project) => <div className="project-card" key={project.id}><div className="summary-icon"><FolderKanban size={17} /></div><div><strong>{project.name}</strong><span>{project.client?.name}</span></div><div className="project-rate">{formatCurrency(project.hourly_rate)}<small>/ hora</small></div><button className="mini-action" onClick={() => edit(project)} aria-label={`Editar ${project.name}`} title="Editar projeto"><Pencil size={15} /></button><button className="mini-action danger project-delete" onClick={() => remove(project)} aria-label={`Excluir ${project.name}`} title="Excluir projeto"><Trash2 size={15} /></button></div>)}{!projects.length && <EmptyState text="Cadastre seu primeiro projeto." />}</div></section></div></div>
}
